### ISSUE TITLE
Add engaging rewards (voting, daily bonuses)

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#13]
I’m using [ProVotes](https://www.spigotmc.org/resources/provotes-1-7-1-11-increase-player-voting.23672/) and [CrateKeys](https://www.spigotmc.org/resources/cratekeys.1040/).

+ What should the regular, most elementary rewards be?
+ What rewards should be chance based?
+ What rewards should you get for voting daily?

I’d also be re-missed not to mention [DailyBonus](https://www.spigotmc.org/resources/daily-bonus-1-7-1-11-increase-player-retention.13974/?update=56400) which isn’t about voting but just playing.

We could do a lot here, but I need some ideas. Getting $500 for voting every time is boring.

**Comment by owengraven** [comment]
I would be up for a system where voting gives you a key, and you open a crate with random drops. 

Voting in minecraft in my opinion should give you something you can't easely or get without voting, since then you'll want to vote to get it.

What you could also do is when voting giving people bank slips, that they can exchange at the bank for an amount of money (randomized or not). (like cheques works) that way you create more reason to travel around in the server.
